[project]
name = 'Paradox-Resolution-Network'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.paradox-detection]
path = 'contracts/paradox-detection.clar'
clarity_version = 2
epoch = 2.5

[contracts.paradox-resolution-nft]
path = 'contracts/paradox-resolution-nft.clar'
clarity_version = 2
epoch = 2.5

[contracts.resolution-management]
path = 'contracts/resolution-management.clar'
clarity_version = 2
epoch = 2.5

[contracts.timeline-integrity]
path = 'contracts/timeline-integrity.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
